global proc AEzMappedWrapDeformerTemplate(string $nodeName)
{
    print "xxx\n";
    editorTemplate -beginScrollLayout;
    editorTemplate -suppress "inputTarget";
    editorTemplate -suppress "vertexIndex";
    editorTemplate -suppress "vertexIndex";
    editorTemplate -suppress "weightList";
    AEgeometryFilterCommon $nodeName;
    AEgeometryFilterInclude $nodeName;
    editorTemplate -addExtraControls;
    editorTemplate -endScrollLayout;
}
